name: Linting
on:
  workflow_dispatch:
    paths:
      - '**.sh'
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: Shellcheck scripts
    runs-on: ubuntu-20.04
    steps:

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shellcheck
        run: shellcheck *.sh
