name: Nightly Builds
on:
  workflow_dispatch:
  schedule:
    - cron: "37 22 * * *"

jobs:
  periodic_release_head:
    name: Periodic Release for HEAD
    runs-on: ubuntu-20.04
    steps:

      - name: Get operator-sdk
        run: curl --output operator-sdk -JL https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
        env:
          RELEASE_VERSION: v0.19.4

      - name: Get opm
        run: curl --output opm -JL https://github.com/operator-framework/operator-registry/releases/download/$RELEASE_VERSION/linux-amd64-opm
        env:
          RELEASE_VERSION: v1.18.0

      - name: Install jq
        run: sudo apt-get install -y jq sed

      - name: Make operator-sdk executable
        run: chmod +x operator-sdk

      - name: Move operator-sdk binary
        run: sudo mv operator-sdk /usr/local/bin

      - name: Make opm executable
        run: chmod +x opm

      - name: Move opm binary
        run: sudo mv opm /usr/local/bin

      - name: Get Smart Gateway Operator
        uses: actions/checkout@v2
        with:
          repository: infrawatch/smart-gateway-operator
          path: smart-gateway-operator

      - name: Get Service Telemetry Operator
        uses: actions/checkout@v2
        with:
          repository: infrawatch/service-telemetry-operator
          path: service-telemetry-operator

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: release-automation

      - name: Run release builder
        run: ${{ github.workspace }}/release-automation/releaser.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          QUAY_INFRAWATCH_OPERATORS_USERNAME: ${{ secrets.QUAY_INFRAWATCH_OPERATORS_USERNAME }}
          QUAY_INFRAWATCH_OPERATORS_PASSWORD: ${{ secrets.QUAY_INFRAWATCH_OPERATORS_PASSWORD }}

  periodic_release_1_5:
    name: Periodic Release for STF 1.5
    runs-on: ubuntu-20.04
    steps:

      - name: Get operator-sdk
        run: curl --output operator-sdk -JL https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu
        env:
          RELEASE_VERSION: v0.19.4

      - name: Get opm
        run: curl --output opm -JL https://github.com/operator-framework/operator-registry/releases/download/$RELEASE_VERSION/linux-amd64-opm
        env:
          RELEASE_VERSION: v1.18.0

      - name: Install jq
        run: sudo apt-get install -y jq sed

      - name: Make operator-sdk executable
        run: chmod +x operator-sdk

      - name: Move operator-sdk binary
        run: sudo mv operator-sdk /usr/local/bin

      - name: Make opm executable
        run: chmod +x opm

      - name: Move opm binary
        run: sudo mv opm /usr/local/bin

      - name: Get Smart Gateway Operator
        uses: actions/checkout@v2
        with:
          repository: infrawatch/smart-gateway-operator
          path: smart-gateway-operator
          ref: stable-1-5-metadata-update

      - name: Get Service Telemetry Operator
        uses: actions/checkout@v2
        with:
          repository: infrawatch/service-telemetry-operator
          path: service-telemetry-operator
          ref: stable-1-5-metadata-update

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: release-automation

      - name: Run release builder
        run: ${{ github.workspace }}/release-automation/releaser.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          QUAY_INFRAWATCH_OPERATORS_USERNAME: ${{ secrets.QUAY_INFRAWATCH_OPERATORS_USERNAME }}
          QUAY_INFRAWATCH_OPERATORS_PASSWORD: ${{ secrets.QUAY_INFRAWATCH_OPERATORS_PASSWORD }}
          BUNDLE_TAG: "stable-1.5"
          INSPECTION_TAG: "stable-1.5"
          INDEX_IMAGE_TAG: "nightly-1.5"
